### ISSUE TITLE
Document how to run a local instance 

### ISSUE THREAD

**Issue by arthurlutz** [bfirsh/whiskerboard#1]
... without deploying to ep.io

**Comment by arthurlutz** [comment]
I got something more or less working with : 

 fab setup 
 edit settings/base.py (the postgresql settings)
 createdb whiskerboard
 python manage.py syncdb
 python manage.py runserver

**Comment by bsdlp** [comment]
@arthurlutz, would #14 be sufficient to close out this issue?
