### ISSUE TITLE
update whiskerboard with latest stashboard changes

### ISSUE THREAD

**Issue by bsdlp** [bfirsh/whiskerboard#4]
Looks like whiskerboard is 2 years out of date and nobody is really maintaining it. Is there a fork that's more up to date that can be promoted to the "official" whiskerboard fork?

**Comment by bfirsh** [comment]
I'd happily maintain it.

@sijis, @ametaireau, @jvasallo – what do you think? It's be great to get your changes merged in.

**Comment by almet** [comment]
yup, let's do that :+1:

**Comment by bsdlp** [comment]
Would it also be possible to remove further vendor lock-in by removing the ep.io references (especially since ep.io is no mo)?

**Comment by bfirsh** [comment]
Sounds like a good idea.

**Comment by bfirsh** [comment]
@ametaireau Any chance you could open PRs for anything you want merged back in?

**Comment by almet** [comment]
I just did a PR with my changes https://github.com/bfirsh/whiskerboard/pull/5

**Comment by jvasallo** [comment]
The branch @sijis worked on features a lot the api features missing from whiskerboard. We created a dynamic api for updating and getting info from sources. We also did a lot of the work of cleaning up the code to bare bones. I mainly worked on the porting of the application to 1.5.x series of django.

**Comment by bfirsh** [comment]
@fly I've added you as a collaborator if you want to help maintain :)

**Comment by bsdlp** [comment]
thanks @bfirsh

**Comment by sijis** [comment]
It looks like i'm a bit late to the discussion, but it'll still put in my thoughts.

I personally haven't liked the direction stashboard has taken with adding some of the twitter tie-ins. What i did initially like about it was that it was simple. What brought me to whiskerboard is that it wasn't tied to appengine and it was also simple. The only lacking feature was the api (which my fork added).

I would lean towards keeping whiskerboard simple. I'm not sure how it could be done, but tie-ins to twitter or other social media things should be done via a plug-in type feature, as opposed to 'core'.

As a side though a recent fork from my fork (which was then renamed) added a 'notice' type feature, which looked like if someone added a 'notice' it would put it on the top of the dashboard. I think things like that are a great thing to add.
